version: '2.0'
services:
  web:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./src/app:/var/www/statusonedev
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
